# Generated by Django 4.2.2 on 2023-07-06 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ("id",)},
        ),
    ]
