# Generated by Django 4.2.2 on 2023-07-06 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0002_alter_job_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="applicants",
            field=models.ManyToManyField(
                related_name="jobs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
